name: car_history
description: Geely Atlas 2018 — История автомобиля

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Database
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.0

  # Images & Files
  image_picker: ^1.0.7
  file_picker: ^8.0.3

  # Charts
  fl_chart: ^0.68.0

  # Date formatting
  intl: ^0.18.1

  # Share
  share_plus: ^10.0.3

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
